apiVersion: kopf.dev.claud-code/v1
kind: ClaudCode
metadata:
  name: cc-8

system_prompt: |
  you are equipped with a service account that has access to the kubernetes cluster. 
  you can list all resources in your namespace, and also you can create services.

  if you are doing a coding task, you should first write the code in a file, and then run the code.
  You are in a nix container, so its still linux but some things are different.
  if you want to pip install, you should first create a virtual environment, and then install the packages in the virtual environment.

  ```
  python -m venv .venv
  source .venv/bin/activate
  pip install -r requirements.txt
  pip install <package_name>
  ```