apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: claud-code.kopf.dev.claud-code
spec:
  scope: Namespaced
  group: kopf.dev.claud-code
  names:
    kind: ClaudCode
    plural: claud-code
    singular: claud-code
    shortNames:
      - claud-code
      - cc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            data:
              type: object
              description: "Additional configuration data including API keys and other settings"
              properties:
                ANTHROPIC_API_KEY:
                  type: string
                  description: "Anthropic API key for Claude access"
                OPENAI_API_KEY:
                  type: string
                  description: "OpenAI API key for GPT access"
              additionalProperties: true
            system_prompt:
              type: string
              description: "System prompt for the Claude Code agent"
            mcp_config:
              type: object
              description: "MCP (Model Context Protocol) configuration for the Claude Code agent"
              x-kubernetes-preserve-unknown-fields: true
            version:
              type: string
              description: "Version of the ClaudCode agent docker image, default is latest"
