# kopf-example namespace
apiVersion: v1
kind: Namespace
metadata:
  name: kopfexample

# kopf-example operator deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopfexample-operator
  namespace: kopfexample
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: kopfexample-operator
  template:
    metadata:
      labels:
        application: kopfexample-operator
    spec:
      serviceAccountName: kopfexample-account
      containers:
      - name: the-only-one
        image: wholelottahoopla/kopf-agent:ff419a374e4b46a54667e40bbd5ff4f60a647e3c
        imagePullPolicy: Always
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: anthropic-api-key
              key: ANTHROPIC_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: OPENAI_API_KEY